apiVersion: v2
name: pet-battle-infra
description: A Helm chart for Pet Battle Infrastructure
type: application
version: 1.0.0
appVersion: 1.0.0
home: https://petbattle.github.io/helm-charts
maintainers:
- name: eformat
- name: noelo
