apiVersion: v2
name: pet-battle-infra
description: Pet Battle Infrastructure
type: application
version: 1.0.25
appVersion: 1.0.0
home: https://petbattle.github.io/helm-charts
icon: https://avatars1.githubusercontent.com/u/68044996?s=200&v=4
maintainers:
- name: eformat
- name: noelo
