{{- if and .Values.certutil.enabled .Values.subscriptions.only }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-utils-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: cert-utils-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cert-utils-operator.v1.0.0
{{- end }}
