{{- if .Values.keycloak.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak-operator
  generation: 1
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: keycloak-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: keycloak-operator.v12.0.1
---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: pbkeycloak
  labels:
    app: pbkeycloak
    {{- include "pet-battle-infra.labels" . | nindent 4 }}
spec:
  instances: 1
  externalAccess:
    enabled: true
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: pbserver
  labels:
    client: pbserver
spec:
  realmSelector:
    matchLabels:
      realm: pbrealm
  client:
    name: pbserver
    clientId: pbserver
    bearerOnly: true
    protocol: openid-connect
    ########################################################
    #TODO : These URLs need to be changed before deployment#
    # The second url is only used for testing              #
    ########################################################
    rootUrl: http://localhost
    redirectUris:
      - "http://localhost:3000/*"
    ########################################################
    standardFlowEnabled: true
    serviceAccountsEnabled: true
    directAccessGrantsEnabled: true
    surrogateAuthRequired: false
    enabled: true
    alwaysDisplayInConsole: false,
    clientAuthenticatorType: "client-secret"
    consentRequired: false
    implicitFlowEnabled: false
    authorizationServicesEnabled: true
    publicClient: false
    frontchannelLogout: false
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    defaultRoles:
      - "pbplayer"
      - "pbviewer"
      - "pbtest"
      - "pbadmin"
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: pbclient
  labels:
    client: pbclient
spec:
  realmSelector:
    matchLabels:
      realm: pbrealm
  client:
    name: pbclient
    clientId: pbclient
    bearerOnly: false
    protocol: openid-connect
    ########################################################
    #TODO : These URLs need to be changed before deployment#
    # The second url is only used for testing              #
    ########################################################
    rootUrl: http://localhost:3000
    redirectUris:
      - "http://localhost:3000/*"
    ########################################################
    standardFlowEnabled: true
    serviceAccountsEnabled: true
    directAccessGrantsEnabled: true
    surrogateAuthRequired: false
    enabled: true
    alwaysDisplayInConsole: false,
    clientAuthenticatorType: "client-secret"
    consentRequired: false
    implicitFlowEnabled: false
    authorizationServicesEnabled: true
    publicClient: false
    frontchannelLogout: false
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    defaultRoles:
      - "pbplayer"
      - "pbviewer"
      - "pbtest"
      - "pbadmin"
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: pbrealm
  labels:
    realm: pbrealm
spec:
  realm:
    realm: "pbrealm"
    enabled: true
    displayName: "Pet Battle Single Sign On Realm"
    loginWithEmailAllowed: true
    registrationAllowed: true
    registrationEmailAsUsername: true
    rememberMe: true
    sslRequired: "external"
  instanceSelector:
    matchLabels:
      app: pbkeycloak
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: myuser
  labels:
    app: pbkeycloak
spec:
  user:
    username: "myuser"
    firstName: "John"
    lastName: "Doe"
    email: "myuser@petbattle.com"
    enabled: true
    credentials:
      - type: "password"
        value: "password"
    clientRoles:
      "pbclient":
        - "pbplayer"
        - "pbviewer"
  realmSelector:
    matchLabels:
      realm: pbrealm
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: pbadmin
  labels:
    app: pbkeycloak
spec:
  user:
    username: "pbadmin"
    firstName: "pbadmin"
    lastName: "pbadmin"
    email: "pbadmin@petbattle.com"
    enabled: true
    credentials:
      - type: "password"
        value: "password"
    realmRoles:
      - "admin"
    clientRoles:
      "pbclient":
        - "pbtest"
        - "pbadmin"
        - "pbplayer"
        - "pbviewer"
      "realm-management":
        - "manage-users"
        - "manage-realm"
        - "view-realm"               
  realmSelector:
    matchLabels:
      realm: pbrealm
{{- end }}
